"""empty message

Revision ID: 16c70b11242e
Revises: 9519d28f13f0
Create Date: 2019-10-02 14:50:27.180692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c70b11242e'
down_revision = '9519d28f13f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('is_main', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'is_main')
    # ### end Alembic commands ###
