"""empty message

Revision ID: bafcadd8390e
Revises: e5b4175be075
Create Date: 2019-10-09 15:34:31.194998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafcadd8390e'
down_revision = 'e5b4175be075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('language', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game_rooms', 'room_languages', ['language'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_rooms', type_='foreignkey')
    op.drop_column('game_rooms', 'language')
    # ### end Alembic commands ###
